language: python
python:
  - '3.8'

branches:
  only:
    - staging

addons:
  chrome: stable

install:
  - pip install pipenv
  - pipenv install


env: DJANGO_SETTINGS_MODULE=purbeurre_project.settings.travis

services:
  - postgresql

script:
  - python manage.py test -v2