version: '3.8'
services:
  web:
    build: .
    command: python /PhotoSite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/PhotoSite
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

