version: '3.8'
services:
  web:
    build: .
    command: python /PhotoSite/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/PhotoSite
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: