# Generated by Django 3.1.4 on 2020-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='theme',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Thème du concours'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='camera',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Appareil photo utilisé'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='global_score',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='Note globale'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='lens',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Objectif utilisé'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Lieu de prise'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='taken_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Date de prise'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='technical',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaires techniques'),
        ),
        migrations.AlterField(
            model_name='review',
            name='calculated_score',
            field=models.FloatField(blank=True, verbose_name='Note calculée'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_global',
            field=models.TextField(blank=True, verbose_name='Commentaire global'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_intention',
            field=models.TextField(blank=True, default=-1, verbose_name='Commentaire intention'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_picture',
            field=models.TextField(blank=True, verbose_name='Commentaire photo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_technical',
            field=models.TextField(blank=True, default=-1, verbose_name='Commentaire technique'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_visual',
            field=models.TextField(blank=True, verbose_name='Commentaire rendu'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_global',
            field=models.IntegerField(blank=True, default=-1, verbose_name='note globale'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_intention',
            field=models.IntegerField(blank=True, default=-1, verbose_name='note intention'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_picture',
            field=models.IntegerField(blank=True, default=-1, verbose_name='note photo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_technical',
            field=models.IntegerField(blank=True, default=-1, verbose_name='note technique'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_visual',
            field=models.IntegerField(blank=True, default=-1, verbose_name='note rendu'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.IntegerField(verbose_name='Note pour une photo et un concours donné'),
        ),
    ]
