# Generated by Django 3.1.4 on 2020-12-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_contest_contest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_image',
            field=models.ImageField(default='#', upload_to='images/', verbose_name='Image du concours'),
        ),
    ]
