# Generated by Django 3.1.4 on 2020-12-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20201216_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='categories',
            field=models.ManyToManyField(blank=True, default='', null=True, to='gallery.Category'),
        ),
    ]
