# Generated by Django 3.1.4 on 2020-12-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20201216_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterField(
            model_name='picture',
            name='file_name',
            field=models.ImageField(upload_to='images/', verbose_name='Fichier image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='calculated_score',
            field=models.FloatField(blank=True, default=0, verbose_name='Note calculée'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_intention',
            field=models.TextField(blank=True, verbose_name='Commentaire intention'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_technical',
            field=models.TextField(blank=True, verbose_name='Commentaire technique'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_global',
            field=models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note globale'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_intention',
            field=models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note intention'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_picture',
            field=models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note photo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_technical',
            field=models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note technique'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_visual',
            field=models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note rendu'),
        ),
    ]
