# Generated by Django 3.1.4 on 2020-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20201220_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_picture',
            field=models.TextField(blank=True, verbose_name='Commentaire rendu image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_picture',
            field=models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note rendu image'),
        ),
    ]
