# Generated by Django 3.1.4 on 2020-12-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20201221_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
