# Generated by Django 3.1.4 on 2020-12-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestpicture',
            name='id_contest',
        ),
        migrations.RemoveField(
            model_name='contestpicture',
            name='id_picture',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='id_contest_picture',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='ContestPicture',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
