# Generated by Django 3.1.4 on 2020-12-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20201223_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='categories',
            field=models.ManyToManyField(to='gallery.Category'),
        ),
    ]
