# Generated by Django 3.1.4 on 2020-12-23 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0011_auto_20201223_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Picture's title", max_length=120, verbose_name='Titre du concours')),
                ('theme', models.CharField(default='', max_length=200, null=True, verbose_name='Thème du concours')),
                ('description', models.TextField(verbose_name='Desciption du concours')),
                ('date_begin_upload', models.DateField(verbose_name='Date de début dépot photo')),
                ('date_end_upload', models.DateField(verbose_name='Date de fin dépot photo')),
                ('date_begin_vote', models.DateField(verbose_name='Date de début du vote')),
                ('date_end_vote', models.DateField(verbose_name='Date de fin du vote')),
                ('archived', models.BooleanField(default=False, verbose_name='Concours archivé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du concours')),
                ('contest_image', models.ImageField(default='#', upload_to='images/', verbose_name='Image du concours')),
            ],
        ),
        migrations.CreateModel(
            name='ContestPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépot photo')),
                ('id_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('id_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.picture')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Note pour une photo et un concours donné')),
                ('date_score', models.DateTimeField(auto_now_add=True, verbose_name='Date de la note')),
                ('id_contest_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contestpicture')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
