# Generated by Django 3.1.4 on 2020-12-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20201223_1618'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='pictures',
            field=models.ManyToManyField(through='contest.ContestPicture', to='gallery.Picture'),
        ),
    ]
