# Generated by Django 3.1.4 on 2020-12-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_pictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestpicture',
            options={'ordering': ['-date_upload']},
        ),
    ]
