# Generated by Django 3.1.4 on 2020-12-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20201228_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='deposit',
            field=models.BooleanField(default=False, verbose_name='Dépot photo autorisé'),
        ),
        migrations.AddField(
            model_name='contest',
            name='vote',
            field=models.BooleanField(default=False, verbose_name='Vote en cours'),
        ),
    ]
