# Generated by Django 3.1.4 on 2020-12-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20201228_1007'),
        ('contest', '0005_auto_20201228_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='vote',
            new_name='vote_open',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='contest_picture',
        ),
        migrations.AddField(
            model_name='vote',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.picture'),
            preserve_default=False,
        ),
    ]
