# Generated by Django 3.1.4 on 2020-12-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20201228_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestpicture',
            name='score_contest',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Score concours'),
        ),
    ]
