# Generated by Django 3.1.4 on 2020-12-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_contestpicture_score_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='picture',
        ),
        migrations.AddField(
            model_name='vote',
            name='contest_picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.contestpicture'),
            preserve_default=False,
        ),
    ]
