# Generated by Django 3.1.4 on 2020-12-23 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0010_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_intention', models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note intention')),
                ('score_technical', models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note technique')),
                ('score_picture', models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note rendu image')),
                ('score_global', models.IntegerField(blank=True, choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], default=0, verbose_name='note globale')),
                ('comment_intention', models.TextField(blank=True, verbose_name='Commentaire intention')),
                ('comment_technical', models.TextField(blank=True, verbose_name='Commentaire technique')),
                ('comment_picture', models.TextField(blank=True, verbose_name='Commentaire rendu image')),
                ('comment_global', models.TextField(blank=True, verbose_name='Commentaire global')),
                ('calculated_score', models.FloatField(blank=True, default=0, verbose_name='Note calculée')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la critique')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
    ]
