# Generated by Django 3.1.4 on 2020-12-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score_global',
            field=models.IntegerField(choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], verbose_name='note globale'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_intention',
            field=models.IntegerField(choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], verbose_name='note intention'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_picture',
            field=models.IntegerField(choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], verbose_name='note rendu image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_technical',
            field=models.IntegerField(choices=[(1, '1 - pas terrible'), (2, '2 - peut mieux faire'), (3, '3 - pas mal'), (4, '4 - bien'), (5, '5 - excellent')], verbose_name='note technique'),
        ),
    ]
